##### START OF CODE #####

# R 4.5.0
library(dplyr)    # 1.1.4
library(tidyr)    # 1.3.1
library(psych)    # 2.5.3
library(merTools) # 0.6.2

# simulate some data
dataSim = 
  data.frame(
    id = 1:250
  ) %>%
  dplyr::mutate(
    Alatent = rnorm(n = nrow(.), mean = 0, sd = 1),
    Atime1 = 1.5*Alatent + rnorm(n = nrow(.), mean = 0, sd = 1),
    Atime2 = 1.5*Alatent + rnorm(n = nrow(.), mean = 0, sd = 1),
    Atime1 = round(Atime1),
    Atime2 = round(Atime2),
    Alatent = NULL,
    Blatent = rnorm(n = nrow(.), mean = 0, sd = 1),
    Btime1 = 0.5*Blatent + rnorm(n = nrow(.), mean = 0, sd = 1),
    Btime2 = 0.5*Blatent + rnorm(n = nrow(.), mean = 0, sd = 1),
    Btime1 = round(Btime1),
    Btime2 = round(Btime2),
    Blatent = NULL
  )

##### COMPARE CORRELATIONS #####

# look at spearman's correlation
with(dataSim, cor(Atime1, Atime2, method = "spearman"))
with(dataSim, cor(Btime1, Btime2, method = "spearman"))

# look at pearson's correlation
with(dataSim, cor(Atime1, Atime2, method = "pearson"))
with(dataSim, cor(Btime1, Btime2, method = "pearson"))

##### COMPARE ICCs GENERATED BY TWO DIFFERENT PACKAGES #####

# 1. look at icc (via psych)

# measure A
psych::ICC(
  # data must be in wide format
  # with extra cols removed
  x = dataSim %>%
    dplyr::select(Atime1, Atime2),
  # other settings
  lmer = TRUE,
  check.keys = TRUE
)

# measure B
psych::ICC(
  # data must be in wide format
  # with extra cols removed
  x = dataSim %>%
    dplyr::select(Btime1, Btime2),
  # other settings
  lmer = TRUE,
  check.keys = TRUE
)

# 2. look at icc (via merTools)

# measure A
merTools::ICC(
  # data must be in long format
  # with ID col included
  data = dataSim %>%
    tidyr::pivot_longer(
      cols = c("Atime1", "Atime2"),
      names_to = "time",
      names_prefix = "time",
      values_to = "rating"
    ),
  # indicate col with the ratings
  outcome = "rating",
  # indicate col with the ID
  group = "id"
)

# measure B
merTools::ICC(
  # data must be in long format
  # with ID col included
  data = dataSim %>%
    tidyr::pivot_longer(
      cols = c("Btime1", "Btime2"),
      names_to = "time",
      names_prefix = "time",
      values_to = "rating"
    ),
  # indicate col with the ratings
  outcome = "rating",
  # indicate col with the ID
  group = "id"
)

##### END OF CODE #####
